# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 399dc92fb39e5319b7e0b87ce4e39c0ff91de43dd146a5864076093b67f34489e1b09d7013a582162c44b48f96055a75ac5ecfe315677207a89b4277133eca46

test:
  secret_key_base: 5cea8c196874bb765c808515eef2d3ce18527cc4c29b3f117872ccb14b0df5a3b54c3056bdea1a7cb67a78a962e8c08a081b12c4da3c674bae6525075b87bb02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
